
namespace Work.YIS.Code.Skills
{
    public enum SkillEnum
    {
        DUMMYSKILL = 0, FIRE_HAND = 1, WIND_HAND = 2, ICE_HAND = 3, NATURE_HAND = 4, ELECTRO_HAND = 5, WATER_HAND = 6, WEAPON_ATTACK = 7, SWORD_SLASH = 8, COMMONARROW = 9, FIREARROW = 10, ICEATTACK = 11, DENDROSKILL = 12, ELECTROATTACK = 13, SMITESKILL = 14, SNAPSKILL = 15, SNAGHARPOON = 16, TORRENTIAL_FLOW = 17, SPIN_ATTACK = 18, LIGHTNING = 19, FROSTGNAW = 20, TIMEHIT = 21, SINGULARITYSKILL = 22, MAGICAL_LEAF = 23, BLADESWHIRLSKILL = 24, LIGHTNING_STRIKE = 25, TAKEDOWN = 26, BATTLESTANCE = 27, FIREBLOW = 28, RAZORLEAF = 29, SCRATCHSKILL = 30, INFERNO = 31, ENEMYHPHEALSKILL = 32, AXEBLOW = 33, SURPRISEATTACK = 34, TRIPLEMETEOR = 35, WHIRLWIND = 36, DEATHMARCH = 37, ICERAIN = 38
    }
}
